import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics />
        <footer className="bg-gray-800 text-white py-4 text-center">
          <p>
            Follow me on X: <a href="https://x.com/0xsk777" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline">@0xsk777</a>
          </p>
          <p>
            Visit my portfolio: <a href="https://oxsk777.vercel.app/" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline">oxsk777.vercel.app</a>
          </p>
        </footer>
      </body>
    </html>
  );
}
