import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Footer() {
  return (
    <footer className="w-full p-4 bg-black bg-opacity-70 text-center text-sm flex items-center justify-center space-x-2">
      <a
        href="https://x.com/0xsk777"
        target="_blank"
        rel="noopener noreferrer"
        className="flex items-center space-x-2 text-white hover:text-gray-300"
      >
        <Image
          src="/x-icon.svg"
          alt="X Icon"
          width={20}
          height={20}
        />
        <span>My X profile @0xsk777</span>
      </a>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
